**Superior Courts:**

- **Constitutional Court** – ZACC
- **Supreme Court of Appeal** – ZASCA

**High Courts:**

- **Eastern Cape Division, Bhisho** – ZAECBHC
- **Eastern Cape Division, Grahamstown** – ZAECGHC
- **Eastern Cape Division, Gqeberha (Port Elizabeth)** – ZAECPEHC
- **Eastern Cape Division, Mthatha** – ZAECMHC
- **Free State Division, Bloemfontein** – ZAFSHC
- **Gauteng Division, Pretoria** – ZAGPPHC
- **Gauteng Local Division, Johannesburg** – ZAGPJHC
- **KwaZulu-Natal Division, Pietermaritzburg** – ZAKZPHC
- **KwaZulu-Natal Local Division, Durban** – ZAKZDHC
- **Limpopo Division, Polokwane** – ZALMPPHC
- **Limpopo Local Division, Thohoyandou** – ZALMPTHC
- **Mpumalanga Division, Mbombela (Nelspruit)** – ZAMPMBHC
- **Mpumalanga Local Division, Middelburg** – ZAMPMHC
- **Northern Cape Division, Kimberley** – ZANCHC
- **North West Division, Mahikeng** – ZANWHC
- **Western Cape Division, Cape Town** – ZAWCHC

**Specialist Courts:**

- **Competition Appeal Court** – ZACAC
- **Competition Tribunal** – ZACT
- **Electoral Court** – ZAEC
- **Equality Court** – ZAEQC
- **Land Claims Court** – ZALCC
- **Labour Appeal Court** – ZALAC
- **Labour Court** – ZALC
- **Tax Court** – ZATC
