# Generated by Django 5.1.6 on 2025-02-21 14:11

import django.db.models.deletion
import pgvector.django.vector
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Judgment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("full_citation", models.TextField(blank=True, null=True)),
                ("court", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "case_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("judgment_date", models.DateField(blank=True, null=True)),
                ("judges", models.TextField(blank=True, null=True)),
                ("text_markdown", models.TextField()),
                (
                    "vector_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                ("saflii_url", models.URLField(blank=True, null=True)),
                ("reportability_score", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["title"], name="semantis_ap_title_c3345f_idx"),
                    models.Index(
                        fields=["case_number"], name="semantis_ap_case_nu_8bff22_idx"
                    ),
                    models.Index(
                        fields=["judgment_date"], name="semantis_ap_judgmen_7e9381_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SearchHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(blank=True, max_length=255, null=True)),
                ("query", models.TextField()),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Search histories",
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="semantis_ap_user_id_01a552_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="semantis_ap_timesta_e91074_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Statute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("act_number", models.CharField(blank=True, max_length=50, null=True)),
                ("year", models.IntegerField(blank=True, null=True)),
                ("text_markdown", models.TextField()),
                (
                    "vector_embedding",
                    pgvector.django.vector.VectorField(
                        blank=True, dimensions=768, null=True
                    ),
                ),
                ("source_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(fields=["title"], name="semantis_ap_title_748900_idx"),
                    models.Index(fields=["year"], name="semantis_ap_year_7ad281_idx"),
                    models.Index(
                        fields=["act_number"], name="semantis_ap_act_num_4ccff9_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SavedCase",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("user_id", models.CharField(max_length=255)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "case",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="semantis_app.judgment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["user_id"], name="semantis_ap_user_id_a68580_idx"
                    ),
                    models.Index(
                        fields=["timestamp"], name="semantis_ap_timesta_4626e7_idx"
                    ),
                ],
                "unique_together": {("user_id", "case")},
            },
        ),
    ]
