# Generated by Django 5.1.6 on 2025-02-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgment",
            name="title",
            field=models.CharField(max_length=1000),
        ),
    ]
