# Generated by Django 5.1.6 on 2025-02-22 08:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0003_textchunk_update_vector_dimensions"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="chunks",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgment",
            name="chunks_embedded",
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name="TextChunk",
        ),
    ]
