# Generated by Django 5.1.6 on 2025-02-22 09:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0004_judgment_chunks_judgment_chunks_embedded_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ScoreValidation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("validation_passed", models.BooleanField(default=False)),
                ("validation_message", models.TextField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "validated_by",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="score_validations",
                        to="semantis_app.judgment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["judgment"], name="semantis_ap_judgmen_40ace7_idx"
                    ),
                    models.Index(
                        fields=["validation_passed"],
                        name="semantis_ap_validat_7d2228_idx",
                    ),
                    models.Index(
                        fields=["validated_at"], name="semantis_ap_validat_05ebb0_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ScoringSection",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("section_name", models.CharField(max_length=255)),
                ("score", models.IntegerField()),
                ("explanation", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "judgment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scoring_sections",
                        to="semantis_app.judgment",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["judgment"], name="semantis_ap_judgmen_555115_idx"
                    ),
                    models.Index(
                        fields=["section_name"], name="semantis_ap_section_830755_idx"
                    ),
                ],
            },
        ),
    ]
