# Generated by Django 5.1.6 on 2025-02-22 10:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0005_scorevalidation_scoringsection"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="neutral_citation_number",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgment",
            name="neutral_citation_year",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
