# Generated by Django 5.1.6 on 2025-02-22 10:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0006_judgment_neutral_citation_number_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="reportability_explanation",
            field=models.TextField(blank=True, null=True),
        ),
    ]
