# Generated by Django 5.1.6 on 2025-02-23 04:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0007_judgment_reportability_explanation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="judgment",
            name="case_number",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name="judgment",
            name="court",
            field=models.TextField(blank=True, max_length=8, null=True),
        ),
    ]
