# Generated by Django 5.1.6 on 2025-02-23 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0008_alter_judgment_case_number_alter_judgment_court"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="long_summary",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgment",
            name="short_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
