# Generated by Django 5.1.6 on 2025-02-26 04:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0009_judgment_long_summary_judgment_short_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
