# Generated by Django 5.1.6 on 2025-03-01 06:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0010_judgment_featured"),
    ]

    operations = [
        migrations.AddField(
            model_name="judgment",
            name="practice_area",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
