# Generated by Django 5.1.6 on 2025-03-01 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0012_userprofile"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="savedcase",
            name="semantis_ap_user_id_a68580_idx",
        ),
        migrations.RenameField(
            model_name="savedcase",
            old_name="user_id",
            new_name="supabase_user_id",
        ),
        migrations.AlterUniqueTogether(
            name="savedcase",
            unique_together={("supabase_user_id", "case")},
        ),
        migrations.AddIndex(
            model_name="savedcase",
            index=models.Index(
                fields=["supabase_user_id"], name="semantis_ap_supabas_97ac45_idx"
            ),
        ),
    ]
