# Generated by Django 5.1.6 on 2025-03-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0014_add_supabase_user_id_to_searchhistory"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchhistory",
            name="ai_response",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="case",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="semantis_app.judgment",
            ),
        ),
        migrations.AddField(
            model_name="searchhistory",
            name="metadata",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
