# Generated by Django 5.1.6 on 2025-03-02 16:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0015_add_fields_to_searchhistory"),
    ]

    # This is a fake migration to sync the model with the existing database schema
    # The database already has ai_response, metadata, and research_judgment_id fields
    # We're just updating the Django model to match what's already in the database
    operations = [
        migrations.RunSQL(
            sql="-- No SQL changes, just updating Django's migration state",
            reverse_sql="-- No SQL changes, just updating Django's migration state",
            hints={'force_no_change': True},
        ),
    ]
