# Generated by Django 5.1.6 on 2025-03-02 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0016_sync_searchhistory_model"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="searchhistory",
            name="semantis_ap_user_id_01a552_idx",
        ),
        migrations.RemoveField(
            model_name="searchhistory",
            name="user_id",
        ),
        migrations.AlterField(
            model_name="searchhistory",
            name="case",
            field=models.ForeignKey(
                blank=True,
                db_column="research_judgment_id",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="semantis_app.judgment",
            ),
        ),
    ]
