# Generated by Django 5.1.6 on 2025-03-02 18:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0017_remove_user_id_from_searchhistory"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgment",
            name="practice_area",
        ),
        migrations.AddField(
            model_name="judgment",
            name="case_name",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name="judgment",
            name="practice_areas",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="judgment",
            name="practice_areas_reasoning",
            field=models.TextField(blank=True, null=True),
        ),
    ]
