# Generated by Django 5.1.6 on 2025-03-03 04:51

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "semantis_app",
            "0018_remove_judgment_practice_area_judgment_case_name_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="BlogCategory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Blog categories",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BlogPost",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("slug", models.SlugField(max_length=255, unique=True)),
                ("content", models.TextField()),
                ("summary", models.TextField(blank=True, null=True)),
                ("image_url", models.URLField(blank=True, max_length=500, null=True)),
                ("image_prompt", models.TextField(blank=True, null=True)),
                ("author", models.CharField(default="Admin", max_length=100)),
                ("is_published", models.BooleanField(default=False)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="posts",
                        to="semantis_app.blogcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BlogComment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("supabase_user_id", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("is_approved", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="semantis_app.blogpost",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(fields=["slug"], name="semantis_ap_slug_30a705_idx"),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["created_at"], name="semantis_ap_created_2264d3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogpost",
            index=models.Index(
                fields=["is_published"], name="semantis_ap_is_publ_f2ed51_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogcomment",
            index=models.Index(
                fields=["supabase_user_id"], name="semantis_ap_supabas_398656_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogcomment",
            index=models.Index(
                fields=["created_at"], name="semantis_ap_created_8566ec_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="blogcomment",
            index=models.Index(
                fields=["is_approved"], name="semantis_ap_is_appr_e7fbd2_idx"
            ),
        ),
    ]
