# Generated by Django 5.1.6 on 2025-03-03 18:38

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("semantis_app", "0019_blogcategory_blogpost_blogcomment_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="judgment",
            name="case_name",
        ),
        migrations.RemoveField(
            model_name="judgment",
            name="practice_areas_reasoning",
        ),
    ]
