name: Test Environment Setup

on:
  workflow_dispatch:  # Manual triggering only
  
jobs:
  test-setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install dependencies with uv
        run: |
          uv venv
          uv pip install -r requirements.txt
      
      - name: List installed packages
        run: |
          uv run pip list
      
      - name: Check Python environment
        run: |
          uv run python --version
          uv run python -c "import sys; print(sys.executable)"
      
      - name: Check run_all_stages.py
        run: |
          uv run python -c "import os; print(os.path.exists('run_all_stages.py')); print(open('run_all_stages.py', 'r').read()[:200] + '...')"
          
      - name: Verify logs directory
        run: |
          mkdir -p logs
          echo "Test log entry" > logs/test.log
          ls -la logs/
          
      - name: Test artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: logs/
          retention-days: 1 