name: Test Environment Setup

on:
  workflow_dispatch:  # Manual triggering only
  push:  # Temporarily add push trigger for testing
    branches:
      - main
  
jobs:
  test-setup:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Debug - List repository contents
        run: |
          echo "Current directory: $(pwd)"
          echo "Repository contents:"
          ls -la
          echo "Checking run_all_stages.py exists:"
          if [ -f "run_all_stages.py" ]; then echo "File exists"; else echo "File does not exist"; fi
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install dependencies with uv
        run: |
          uv venv
          uv pip install -r requirements.txt
      
      - name: List installed packages
        run: |
          uv run pip list
      
      - name: Check Python environment
        run: |
          uv run python --version
          uv run python -c "import sys; print(sys.executable)"
      
      - name: Check run_all_stages.py
        run: |
          echo "Current directory: $(pwd)"
          echo "Checking file: $(ls -la run_all_stages.py 2>/dev/null || echo 'File not found')"
          uv run python -c "import os; print('File exists:', os.path.exists('run_all_stages.py')); print('Files in directory:', os.listdir('.')[:10])"
          
      - name: Verify logs directory
        run: |
          mkdir -p logs
          echo "Test log entry" > logs/test.log
          ls -la logs/
          
      - name: Test artifact upload
        uses: actions/upload-artifact@v4
        with:
          name: test-logs
          path: logs/
          retention-days: 1 